#!/bin/bash
# Lanza cualquier app con la GPU NVIDIA dedicada
# Uso: prime-run steam    o    prime-run %command% (en Steam)

export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

exec "$@"
